NTC: Expanded perf stamp defn for calibration and IntRef support
Kernel timestamps on sync-flow pkts made by the FBclock are available to
RADclock but never used. They are essential however to
(i)  integrated asym calibration
(ii) evolving the TN toward an Internal-based reference replacing
     the impractical and expensive External (DAG) reference
(iii) completing the establishment of a complete real-time benchmarking
      environment with both Int and Ext comparisons.

This commit supports all the above cases, resulting in an expanded
8-tuple view of a Perf timestamp.

In a nutshell the main results are as follows: for NTC nodes such FB
timestamps are now always available, picked up, and inserted into
stamp_t member IntRef, where they are naturally matched as a byproduct
of RAD stamp matching.
The TN may then add External reference timestamps (into a distinct
ExtRef member) as well via the SHM thread, now renamed to EXTREF.
Consumer functions related to SHM and Clockerr functionality are called
as appropriate whenever either Int or Ext timestamps are available, and
are responsible for understanding what to do if both are.
If asym calibration is requested, the calibration functionality
will act on Int timestamps if available. Calibration is not yet
implemented but  handle->calibrate  is defined so the timestamp usage
logic can be completed.

Mode setting to suit needed FB timestamps
- new preset PKTCAP_TSMODE_INTREF (radclock.h) being like
  PKTCAP_TSMODE_FBCLOCK but with nanotime to enable higher precision
  comparisons, and IntRef applications.
  - Updating of functions in pcap-fbsd.c to support it
  - manual hack to ensure nanotime translation needed in update_stamp_queue
- livepcapstamp_init:  now called with mode = PKTCAP_TSMODE_INTREF
- Despite the change in FORMAT, no changes needed in
	extract_vcount_stamp_v3:  as timestamp comparison is via memcmp, not typed
	get_packet_livepcap:      as pcap header saved raw

Restructure of stamp_t timestamp members  (sync_algo.h):
- Reference timestamps now separately held as {Int,Ext}Ref members of
  new type struct bidir_refstamp.
- struct bidir_stamp_perf  has been modified to match, but is not
  currently not used in anger anywhere, in particular not in stamp_t
- thus storage now decoupled from value of stamp_t type, so all ts’s
  always present (even if not populated), stored type-independently.
  This simplifies ts setting across different type/use scenarios.
 - macros PST, PSTB, BD_TUPLE dealing with former complexity retired
 - BST macro now used to access stamp.st.bstamp in most cases

Interpretation and use of  stamp_type_t  types, and “perf” concept:
STAMP_NTP_PERF  [ existing value reinterpreted ]
- As stamp file type:  distinguishes traditional 4tuple from new expanded 8tuple
- As matching mode flag: indicates EXT matching (performed in EXTREF thread)
  is in vogue to match RAD/Int and Ext timestamps
- As Perf processing flag:  type indicates SHM and Clockerr processing
  required hence process_perfstamp must be called and perfdata defined.
  This is only relevant for the TN but could be live or dead.
  [In future could be set to trigger perfstamp processing based on IntRef only]
STAMP_NTP_INT   [ new value, used when running live only ]
- As stamp file type: NONE!  all non-classic now have STAMP_NTP_PERF 8col format
- As matching mode flag:  indicates {client,server} mode matching
  (performed in PROC thread) is in vogue to generate ‘RAD’ stamp.
  When this is done, and if ExtRef processing needed, value is changed
  to STAMP_NTP_PERF and stamp is sent to EXTREF thread.
- As Perf processing flag:  indicates IntRef timestamps available for
  processing by process_perfstamp if needed (eg if node is the TN)
- As calibration processing flag:  indicates IntRef timestamps available
  for calibration use within process_stamp if needed.
STAMP_NTP
- indicate are in the simple traditional case, IntRef and/or ExtRef
  timestamps need not be populated nor acted on

Setting of Internal timestamps in stamp_t  (create_stamp.c)
- update_stamp_queue:  [used for RADstamp creation, not  PERF stamp]
  if IntRef use activated  (currently only for calibration) access pcap timestamp,
  transform to correct format, and pass to push_ fns, else pass 0.
- push_{client,server}_halfstamp:  setting type to STAMP_NTP_INT in all cases,
  since this code only used for RAD stamp assembly in NTC nodes running
  live, that will always (henceforth) collect INT timestamps as a byproduct
  of {client,server} matching.
 Thus normal NTP type is for replay of traditional data files only.
 Caveat:  if raw replay of perf stamps is ever supported, the type setting
 may be more complex and will have to be revisited.
- insertandmatch_halfstamp:
  Place INT and EXT ts’s in correct fields according to mode.
  Remove superfluous (and now incorrect) mode based type setting.
  stamp->type now only used for verbosity, with STAMP_NTP_INT
  grouped with STAMP_NTP to denote RAD type matching.
- get_fullstamp_from_queue_andclean:
  STAMP_NTP_INT type used to select correct matching paradigm.
  Change  DAG —> EXT  for greater generality and consistency

ASCII stamp file reading/writing
- Header version bump: Version 1—>2   [asciistamp_get_next]
  - extension to 8tuple Perf stamps, not backward compat to V1
  - one-off V1->V2 conversion code kept commented out
  - Ref stamp dirn convention change to FInally respect time order: In,Out —> Out,In
    Ta Tb Te Tf IntRefOut IntRefIn ExtRefOut ExtRefIn [sID]
- open_output_stamp:    trivial changes to write extended PERF stamp,
  for types  STAMP_NTP_PERF  or  STAMP_NTP_INT

process_stamp   [pthread_dataproc.c]
- Code updates to match new timestamp fields.
- BUG: proper init of stamp variable to ensure when running dead that all
  fields are zero except those read in.
- If EXTREF thread active, stamp type conversion now trivial: timestamps already there .
- Updated conditionals for calling of print_out_syncline and return
  code of 2 to signal PERFstamp availability for subsequent
  process_perfstamp call when running dead.

process_perfstamp   [pthread_extref.c]
- Now called in multiple scenarios covering both OCNs (where stamp type
  is STAMP_NTP_INT) and the TN (stamp type STAMP_NTP_PERF).
- Extra logic in calls to ensure SHMalgo and RADperfeval only called when appropriate.
  - for OCNs, perfdata is not defined and is now avoided.
  - RADperfeval can now operate on either INT or EXT stamps.

radclock_main.c:
- create_handle:  BUG fix:   last_sID wasn’t initialized
- init_handle:  ascii output type now set to NTP_PERF for both the TN
                and OCNs, regardless of EXTREF status
- Definition and use of new fn destroy_perf for
  perf state deallocation on radclock exit, was missing!

Thread name change:  SHM  —>  EXTREF
- Rationale:
  -- describes explicitly what it is and why need a thread:
     integration of asynchronous reference coming from an external source
  -- more accurate given TN uses it for both SHM and clock perf
  -- more specific because if a production TN used Int stamps as Reference
     (no Ext), then it would still be doing  SHM+clockperf, but doing it
     without any Ext and without a thread
  -- thus helps decouple source of reference, from how it is used:

- all affected names changed throughout, and most reference to DAG
  replaced by EXTREF also, consistent with DAG —> EXT matching mode change
- corrected inconsistencies with some of the {server,client} EXTREF
  naming in config_mgr.* and throughout.
  Exception:  retention of keys “shm_server” (config_mgr.c: specifies want
  SHM services), though mapped to value CONFIG_SERVER_EXTREF as currently
  only available via activation of EXTREF.
  Ditto for shm_dag_client which may be removed in future anyway.
- filename change:  pthread_shm.c  —> pthread_extref.c

Conf file / run mode consistency
- Addition checks to avoid incompatibles when running Dead:
   main:                    disabling telemetry
   process_stamp:  disabling auth_key checking

Various ws compliance.